name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
env: # Variables d'environnement au niveau du workflow
  MY_GLOBAL_VAR: "Hello from global"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.15.1
      uses: actions/setup-node@v4
      with:
        node-version: '22.15.1'
    - name: Install dependencies
      run: npm ci
  test:
      runs-on: ubuntu-latest
      env: # Variables d'environnement au niveau du job
        MY_JOB_VAR: "Hello from job"
      steps:
        - name: Access variables
          env: # Variables d'environnement au niveau de l'étape
            MY_STEP_VAR: "Hello from step"
          run: |
            echo "Global variable: $MY_GLOBAL_VAR"
            echo "Job variable: $MY_JOB_VAR"
            echo "Step variable: $MY_STEP_VAR"
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Display secret (DO NOT DO THIS IN REAL LIFE!)
        run: |
          echo "My API Key is: ${{ secrets.MY_API_KEY }}"
          # En production, vous passeriez le secret à un outil ou un script de manière sécurisée,
          # par exemple en tant que variable d'environnement pour une commande de déploiement.
