name: Manual Trigger Workflow

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'KIANGOYI'
        required: true
        default: 'World'
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: choice
        options:
          - dev
          - staging
          - production

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet user
        run: echo "Hello, ${{ github.event.inputs.name }}! Deploying to ${{ github.event.inputs.environment }}."